version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: swen2tourplanner
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swen2tourplanner
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
